-define(ACUTION_ITEMS_MAXNUM,8).
-define(ACUTION_SERCH_TYPE_ALL,0).
-define(ACUTION_SERCH_TYPE_ITEMNAME,1).

-define(ACUTION_MAX_LOG_NUM,10).

-define(ACUTION_SERCH_RECORD_NUM,20).
-define(ACUTION_SERCH_ITEM_RECORD_NUM,12).

-define(ACUTION_OVERDUA_CHECK_DURATION,600000).

-define(ACUTION_OVERDUA_TIME,86400000).

-define(REBACK_ITEM_NUM_ONCE_MAIL,3).

%%3月6日写[小五]（摆摊物品大类型）
-define(AUCTION_ITEM_TYPE_WEAPON,1).			%%武器
-define(AUCTION_ITEM_TYPE_ARMOR,2).				%%防具
-define(AUCTION_ITEM_TYPE_ORNAMENT,3).			%%饰品
-define(AUCTION_ITEM_TYPE_FORGE_PROP,4).		%%锻造道具
-define(AUCTION_ITEM_TYPE_PUNCH_INLAY,5).		%%打孔镶嵌
-define(AUCTION_ITEM_TYPE_PET_PROP,6).			%%宠物道具
-define(AUCTION_ITEM_TYPE_REFINE_MATERIAL,7).	%%炼制材料
-define(AUCTION_ITEM_TYPE_MEDICINE,8).			%%丹药
-define(AUCTION_ITEM_TYPE_TOKEN,9).				%%令牌
-define(AUCTION_ITEM_TYPE_OTHER,12).			%%其他
-define(AUCTION_ITEM_TYPE_MONEY,100).			%%铜钱元宝
%%


%%3月6日写[小五]（摆摊物品职业）
-define(AUCTION_JOB_TYPE_SAMURAI,1).			%%武士
-define(AUCTION_JOB_TYPE_MAGE,2).				%%法师
-define(AUCTION_JOB_TYPE_HUNTER,3).				%%猎手
