-define(CHESS_SPIRIT_TYPE_SINGLE,1).
-define(CHESS_SPIRIT_TYPE_TEAM,2).

-define(CHESS_SPIRIT_SKILL_TYPE_SHARE,1).
-define(CHESS_SPIRIT_SKILL_TYPE_SELF,2).
-define(CHESS_SPIRIT_SKILL_TYPE_CHESS,3).

-define(CHESS_SPIRIT_RESULT_LEAVE,0).
-define(CHESS_SPIRIT_RESULT_FAILED,1).
-define(CHESS_SPIRIT_RESULT_SUCCESS,2).

-define(START_PREPARE_TIME,11000).
-define(GAME_OVER_KICK_TIME,10000).