-record(festival_control,{id,show,starttime,endtime,award_limit_time}).
-record(festival_recharge_gift,{id,needcount,gift}).
-record(festival_recharge_gift_bg,{id,needcount,gift}).
-record(festival_recharge_info,{roleid,lasttime,crystal_num,exchange_info}).
-record(festival_control_background,{id,show,starttime,endtime,award_limit_time}).
-record(role_festival_recharge_data,{roleid,exchange_info}).
