-define(SYSTEM_CHAT_NORAML_KILL_ROLE,1).
-define(SYSTEM_CHAT_ENCHANMENTS,2).
-define(SYSTEM_CHAT_STONEMIX,3).
-define(SYSTEM_CHAT_BOSS_BORN,4).
-define(SYSTEM_CHAT_MONSTER_KILLED,5).
-define(SYSTEM_CHAT_TANGLE_BATTLE_ROLE_KILLED,6).
-define(SYSTEM_CHAT_TANGLE_BATTLE_MONSTER_KILLED,7).
-define(SYSTEM_CHAT_TANGLE_BATTLE_TOP_FIVE,8).
-define(SYSTEM_CHAT_LOOP_TOWER_MASTER,9).
-define(SYSTEM_CHAT_SERIES_KILL_300,10).
-define(SYSTEM_CHAT_SERIES_KILL_400,11).
-define(SYSTEM_CHAT_SERIES_KILL_500,12).
-define(SYSTEM_CHAT_SERIES_KILL_600,13).
-define(SYSTEM_CHAT_SERIES_KILL_700,14).
-define(SYSTEM_CHAT_SERIES_KILL_800,15).
-define(SYSTEM_CHAT_SERIES_KILL_900,16).
-define(SYSTEM_CHAT_VIP_1,17).
-define(SYSTEM_CHAT_VIP_2,18).
-define(SYSTEM_CHAT_VIP_3,19).
-define(SYSTEM_CHAT_VIP_LEVEL_1,20).
-define(SYSTEM_CHAT_VIP_LEVEL_2,21).
-define(SYSTEM_CHAT_VIP_LEVEL_3,22).
-define(SYSTEM_CHAT_SERVICE_SHUTDOWN_AFTER,23).
-define(SYSTEM_CHAT_CHEST_TREASURE,24).
-define(SYSTEM_CHAT_INSTANCE_XUESHAN,25).
-define(SYSTEM_CHAT_INSTANCE_YUHAI,26).
-define(SYSTEM_CHAT_INSTANCE_MOYANLING,27).
-define(SYSTEM_CHAT_INSTANCE_WANMOKU,28).
-define(SYSTEM_CHAT_INSTANCE_DUOLONG,29).
-define(SYSTEM_CHAT_YHZQ_ROLE_KILL,30).
-define(SYSTEM_CHAT_YHZQ_GOT_FLAG,31).
-define(SYSTEM_CHAT_YHZQ_CONTROL_FLAG,32).
-define(SYSTEM_CHAT_YHZQ_SOURCE_1000,33).
-define(SYSTEM_CHAT_YHZQ_SOURCE_1500,34).
-define(SYSTEM_CHAT_YHZQ_SOURCE_1800,35).
-define(SYSTEM_CHAT_FIRST_CHARGE,36).
-define(SYSTEM_CHAT_MALL_RESTRICT,37).
-define(SYSTEM_CHAT_GUILD_ROLE_KILLED,38).
-define(SYSTEM_CHAT_TREASURE_SPAWNS_LAST_SECTION,49).
-define(SYSTEM_CHAT_TREASURE_SPAWNS_PREPARE,50).
-define(SYSTEM_CHAT_TREASURE_SPAWNS_FIRST_SECTION,51).
-define(SYSTEM_CHAT_TREASURE_SPAWNS_END,52).
-define(SYSTEM_CHAT_TREASURE_SPAWNS_SECTION,53).
-define(SYSTEM_CHAT_TREASURE_SPAWNS_DETAIL,54).
-define(SYSTEM_CHAT_TREASURE_SPAWNS_GOT,55).
-define(SYSTEM_CHAT_ANSWER_TOP3,56).
-define(SYSTEM_CHAT_ANSWER_DETAIL,57).
-define(SYSTEM_CHAT_BOSS_TREASURE_1,58).
-define(SYSTEM_CHAT_BOSS_TREASURE_2,59).
-define(SYSTEM_CHAT_BOSS_TREASURE_3,60).
-define(SYSTEM_CHAT_ZULONG_TREASURE_BOSS_1,61).
-define(SYSTEM_CHAT_ZULONG_TREASURE_BOSS_2,62).
-define(SYSTEM_CHAT_ZULONG_TREASURE_BOSS_3,63).
-define(SYSTEM_CHAT_ZULONG_TREASURE_BOSS_4,64).
-define(SYSTEM_CHAT_ZULONG_TREASURE_BOSS_KILL,65).
-define(SYSTEM_CHAT_VIP_4,72).
-define(SYSTEM_CHAT_VIP_LEVEL_4,73).
-define(SYSTEM_CHAT_EQUIPMENT_EHCHANT,74).
-define(SYSTEM_CHAT_EQUIPMENT_RECAST,75).
-define(SYSTEM_CHAT_FLUSH_SALES_ITEM,79).
-define(SYSTEM_CHAT_QUALITY_REACH_INDEX,110).
-define(SYSTEM_CHAT_QUALITY_EDGE_31,120).
-define(SYSTEM_CHAT_QUALITY_EDGE_61,121).
-define(SYSTEM_CHAT_QUALITY_EDGE_91,122).
-define(SYSTEM_CHAT_QUALITY_EDGE_121,123).
-define(SYSTEM_CHAT_RANDOM_QUALITY,130).				%%pet quality random with 3
-define(SYSTEM_CHAT_PET_TALENT_POWER,140).
-define(SYSTEM_CHAT_PET_TALENT_HITRATE,141).
-define(SYSTEM_CHAT_PET_TALENT_CRITICALRATE,142).
-define(SYSTEM_CHAT_PET_TALENT_STAMINA,143).
-define(SYSTEM_CHAT_CHAT_EVOLUTION,150).

%%programe use
-define(SYSTEM_CHAT_DRAGON_FIGHT_START,1000).
-define(SYSTEM_CHAT_STAR_SPAWNS_PREPARE,1001).
-define(SYSTEM_CHAT_STAR_SPAWNS_FIRST_SECTION,1002).
-define(SYSTEM_CHAT_STAR_SPAWNS_SECTION,1003).
-define(SYSTEM_CHAT_STAR_SPAWNS_LAST_SECTION,1004).
-define(SYSTEM_CHAT_STAR_SPAWNS_END,1005).
-define(SYSTEM_CHAT_EQUIPMENT_UPGRADE,1006).
-define(SYSTEM_CHAT_TRAVEL_BOSS_BORN,1007).
-define(SYSTEM_CHAT_TRAVEL_NORAML_KILL_ROLE,1008).
-define(SYSTEM_CHAT_TRAVEL_MONSTER_KILLED,1009).
-define(SYSTEM_CHAT_GET_MALL_ITEM,1011).
-define(SYSTEM_CHAT_RIDE_SPAWNS_DETAIL,1020).
-define(SYSTEM_CHAT_RIDE_SPAWNS_PREPARE,1021).
-define(SYSTEM_CHAT_RIDE_SPAWNS_FIRST_SECTION,1022).
-define(SYSTEM_CHAT_RIDE_SPAWNS_SECTION,1023).
-define(SYSTEM_CHAT_RIDE_SPAWNS_LAST_SECTION,1024).
-define(SYSTEM_CHAT_RIDE_SPAWNS_END,1025).

-define(SYSTEM_CHAT_EVERQUEST_REFRESH,1090).
-define(SYSTEM_CHAT_TREASURE_TRANSPORT_REFRESH,1091).

-define(SYSTEM_CHAT_RANK_TYPE_1,1101).
-define(SYSTEM_CHAT_RANK_TYPE_2,1102).
-define(SYSTEM_CHAT_RANK_TYPE_3,1103).
-define(SYSTEM_CHAT_RANK_TYPE_4,1104).
-define(SYSTEM_CHAT_RANK_TYPE_5,1105).
-define(SYSTEM_CHAT_RANK_TYPE_6,1106).
-define(SYSTEM_CHAT_RANK_TYPE_7,1107).
-define(SYSTEM_CHAT_RANK_TYPE_8,1108).

-define(SYSTEM_CHAT_ITEM_IDENTIFY,1112).
-define(SYSTEM_CHAT_PET_SYNTHESIS,1113).

-define(SYSTEM_CHAT_ROLE_KILL_50,1120).
-define(SYSTEM_CHAT_ROLE_KILL_100,1121).
-define(SYSTEM_CHAT_GOT_OUT_PRISON,1122).
-define(SYSTEM_CHAT_PUTIN_PRISON,1123).

-define(SYSTEM_CHAT_COM_TREASURE_TRANSPORT,1125).
-define(SYSTEM_CHAT_ROB_TREASURE_TRANSPORT,1127).
-define(SYSTEM_CHAT_SERVER_TREASURE_TRANSPORT_START,1128).

-define(SYSTEM_CHAT_GUILDBATTLE_WINNER,1129).
-define(SYSTEM_CHAT_COUNTRY_GENERAL,1130).
-define(SYSTEM_CHAT_COUNTRY_SOLIDER,1131).
-define(SYSTEM_CHAT_KING_BLOCKTALK,1132).
-define(SYSTEM_CHAT_KING_REMIT,1133).
-define(SYSTEM_CHAT_KING_PUNISH,1134).

-define(SYSTEM_CHAT_JSZD_BATTLE_KILL_SHUIJING,1136).
-define(SYSTEM_CHAT_JSZD_BATTLE_GUILD_REWARD,1137).

-define(SYSTEM_CHAT_GUILD_BONFIRE_START,1139).

-define(SYSTEM_CHAT_MALL_9999,9999).


































