-define(ITEM_TYPE_VIP_CARD_MONTH,1).
-define(ITEM_TYPE_VIP_CARD_SEASON,2).
-define(ITEM_TYPE_VIP_CARD_HALFYEAR,3).
-define(ITEM_TYPE_VIP_CARD_WEEK,4).
-define(ITEM_TYPE_VIP_CARD_NEW_MONTH,5).
-define(ITEM_TYPE_VIP_CARD_NEW_SEASON,6).
-define(ITEM_TYPE_VIP_CARD_NEW_HALFYEAR,7).
-define(ITEM_TYPE_VIP_CARD_EXPERIENCE,8).
-define(ITEM_TYPE_VIP_CARD_3DAY,9).


-define(INFINITE,0).

